### ISSUE TITLE
Moving pieces from one plane to another e.g Earth to Heaven

### ISSUE THREAD

**Issue by thorulf4** [NicEastvillage/ChessHeavenAndHell#29]

**Comment by NicEastvillage** [comment]
In PowerPoint I would cut+paste the piece to another plane. That should work here too xD But I am also considering if off-the-board pieces should be rendered in every plane, resembling having pieces standing next to the board when playing normal physical chess. So: Put the piece next to the board, switch dimension, put it on the board again.

I may sound tedious, but having that space outside the board is a great utility. It will also play nice with that auto-capturing we were talking about in Discord: If you put a piece onto another piece, the "captured" piece will be moved to an empty space outside the board. From here you can easily put it onto another plane or delete it. Whatever is relevant.

**Comment by thorulf4** [comment]
I really like this approach! Although I would also like the ability for piece selections to be alive across plane switches so you could select a piece in one plane and right click to move in another plane

**Comment by NicEastvillage** [comment]
If we can have some visual indicator that something is selected in another plane, then that's okay with me.

**Comment by thorulf4** [comment]
At the very least the selected piece menu will be active on the right. But we might need more of an indicator
